const titles = [  
   'Amazing Politician',
   'Beloved and Respected General',
   'Beloved and Respected Leader',
   'Beloved Father',
   'Bright Sun of Juche',
   'Bright Sun of Pudank',
   'Bright Sun of the 21st Century',
   'Brilliant Leader',
   'Commander-in-Chief',
   'Dear Father',
   'Dear Leader, who is a perfect incarnation of the appearance that a leader should have',
   'Dear Leader',
   'Eternal General Secretary of the Party',
   'Ever-Victorious, Iron-Willed Commander',
   'Fate of the Nation',
   'Father of the Nation',
   'Father of the People',
   'General',
   'Glorious General, Who Descended From Heaven',
   'Great Defender',
   'Great General',
   'Great Leader of our Party and of our Nation',
   'Great Leader',
   'Great Leader',
   'Great Man, Who Descended From Heaven',
   'Great Man, Who Is a Man of Deeds',
   'Great Marshal',
   'Great Sun of the 21st Century',
   'Great Sun of The Nation',
   'Guarantee of the Fatherland\'s Unification',
   'Guiding Star of the 21st Century',
   'Guiding Sun Ray',
   'Highest Incarnation of the Revolutionary Comradeship',
   'His Excellency',
   'Invincible and Triumphant General',
   'Leader of the 21st Century',
   'Leader of the Party and the People',
   'Leader of the Party, the country, and the Army',
   'Leader of the Revolutionary Armed Forces',
   'Leader',
   'Mastermind of the Revolution',
   'Party Centre/Center of the Party',
   'Peerless Leader',
   'Respected Leader',
   'Savior',
   'Shining Star of Paektu Mountain',
   'Sun of Socialism',
   'Sun of the Communist Future',
   'Sun of the Nation',
   'Superior Person',
   'Supreme Leader of the Nation',
   'Symbol of the Fatherland\'s Unification',
   'The Great Sun of Life',
   'Unique Leader',
   'Wise Leader',
   'World Leader of The 21st Century',
]
